name: Java CI with Maven and AsciiDoc

on:
  push:
    branches:
      - Developpement
  pull_request:
    branches:
      - Developpement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Generate AsciiDoc Documentation
      run: asciidoctor -o docs/index.html docs/documentation.adoc

    - name: Convert AsciiDoc to PDF
      run: docker run --rm -v $PWD:/documents asciidoctor/docker-asciidoctor asciidoctor-pdf -o docs/documentation.pdf docs/documentation.adoc

    - name: Build with Maven (Again, if necessary)
      run: mvn -B package --file pom.xml

    - name: Publish JAR or WAR and Documentation as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          target/
          docs/

    - name: Display Artifact URL
      run: |
        ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref }}/my-artifact/"
        echo "Latest Artifact URL: $ARTIFACT_URL"
        echo "##[set-output name=artifact_url;]$ARTIFACT_URL"
      env:
        ARTIFACT_URL: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref }}/my-artifact/
