name: Java CI with Maven

on:
  push:
    branches:
      - Developpement
  pull_request:
    branches:
      - Developpement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install Asciidoctor and Asciidoctor PDF
      run: |
        sudo apt-get install -y asciidoctor
        gem install asciidoctor-pdf --version '< 2.0' --install-dir=./gems
        export PATH=$PATH:./gems/bin

    - name: Generate AsciiDoc Documentation
      run: asciidoctor -o docs/index.html docs/documentation.adoc

    - name: Update Asciidoctor PDF gem
      run: |
        gem update asciidoctor-pdf --user-install
        export PATH=$HOME/.gem/ruby/*/bin:$PATH
      working-directory: $GITHUB_WORKSPACE

    - name: Convert AsciiDoc to PDF
      run: |
        ./gems/bin/asciidoctor-pdf -o docs/documentation.pdf docs/documentation.adoc
      working-directory: $GITHUB_WORKSPACE

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish JAR or WAR and Documentation as Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: |
          target/
          docs/

    - name: Display Artifact URL
      run: |
        ARTIFACT_URL="${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref }}/my-artifact/"
        echo "Latest Artifact URL: $ARTIFACT_URL"
        echo "##[set-output name=artifact_url;]$ARTIFACT_URL"
      env:
        ARTIFACT_URL: ${{ github.server_url }}/${{ github.repository }}/raw/${{ github.ref }}/my-artifact/
